### ISSUE TITLE
Enlaces sin respuesta

### ISSUE THREAD

**Issue by LanderU** [erlerobot/erle_gitbook_cplusplus#16]
En el apartado de "Exercices: Basic" los enlaces de las soluciones no están disponibles.

**Comment by vmayoral** [comment]
@LanderU te he añadido como colaborador en el GitBook. Deberías poder editarlo (lo más sencillo es utilizar el editor online). ¿Podrías revisarlo?

**Comment by silvianunez** [comment]
En Github están colgadas, pero no se ha vertido el contenido al Gitbook.io
