### ISSUE TITLE
Gitbook roto

### ISSUE THREAD

**Issue by ahcorde** [erlerobot/erle_gitbook_cplusplus#2]
Hola @vmayoral y @silvianunez, 

acabo de comenzar a leer el gitbook de C++ [1] y el enlace a la primera pagina esta roto. Me pasa con los dos primero temas. 

[1]http://erlerobotics.gitbooks.io/erle-robotics-c-gitbook/

**Comment by imuguruza** [comment]
Creo que es debido a que las carpetas y ficheros contienen el caráter '+'. Quitándolos debería funcionar
